```yaml
# CreatorSync – ci.yml (v1.0.0)
# --------------------------------------
# GitHub Actions workflow for automated testing and linting
# Investor Note: CI/CD pipeline demonstrates production readiness and code quality
# --------------------------------------

name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
      - name: Lint code
        run: npm run lint
      - name: Check .gitignore
        run: git diff --name-only | grep -E '\.env|node_modules|logs|uploads|recordings' && exit 1 || exit 0
    # ❖ Automated testing and linting ensure robust, scalable code
```
